stages:
  - publish

variables:
  APPLICATION_NAME: auto-crud
  CONTAINER_TAG: ${CI_COMMIT_TAG}
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

npm:
  image: node:20
  stage: publish
  only:
    - tags
  tags:
    - moreillon
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - npm i
    - npm run compile
    - npm publish --access=public

container:
  stage: publish
  only:
    - master
  tags:
    - tags
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
  script:
    - docker build -t ${CONTAINER_IMAGE_LATEST} .
    - docker tag ${CONTAINER_IMAGE_LATEST} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_TAGGED}
