import swaggerAutogen from "swagger-autogen"
import { version, name } from "./package.json"

const generate = swaggerAutogen()

const doc = {
  info: {
    version,
    title: name,
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
}

const outputFile = "./swagger-output.json"
const endpointsFiles = ["./server.ts"]

generate(outputFile, endpointsFiles, doc)
